// ***********************************************************************
// Assembly         : Vavoom
// Author           : Michael Rose
// Created          : 05-20-2019
//
// Last Modified By : Michael Rose
// Last Modified On : 05-20-2019
// ***********************************************************************
// <copyright file="ExposedClass.cs" company="Heartland Payment Systems">
//     Copyright (c) Heartland Payment Systems, Inc.. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Reflection;

namespace Vavoom
{
    /// <summary>
    /// Class ExposedClass.
    /// </summary>
    /// <seealso cref="System.Dynamic.DynamicObject" />
    /// <autogeneratedoc />
    public class ExposedClass : DynamicObject
    {
        private readonly Type _type;
        private readonly Dictionary<string, Dictionary<int, List<MethodInfo>>> _staticMethods;
        private readonly Dictionary<string, Dictionary<int, List<MethodInfo>>> _genStaticMethods;

        private ExposedClass(Type type)
        {
            _type = type;

            _staticMethods = StaticMethods(_type);

            _genStaticMethods = GenStaticMethods(_type);

            var baseType = _type.BaseType;

            while (baseType != null)
            {
                var staticMethods = StaticMethods(baseType);

                foreach (var (key, value) in staticMethods)
                {
                    if (_staticMethods.ContainsKey(key))
                        continue;
                    _staticMethods.Add(key, value);
                }

                var genStaticMethods = GenStaticMethods(baseType);

                foreach (var (key, value) in genStaticMethods)
                {
                    if(_genStaticMethods.ContainsKey(key))
                        continue;
                    _genStaticMethods.Add(key, value);
                }

                baseType = baseType.BaseType;
            }
        }


        private Dictionary<string, Dictionary<int, List<MethodInfo>>> GenStaticMethods(Type type)
        {
            return type
                .GetMethods(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Static)
                .Where(m => m.IsGenericMethod)
                .GroupBy(m => m.Name)
                .ToDictionary(
                    p => p.Key,
                    p => p.GroupBy(r => r.GetParameters().Length).ToDictionary(r => r.Key, r => r.ToList()));
        }

        private Dictionary<string, Dictionary<int, List<MethodInfo>>> StaticMethods(Type type)
        {
            return type
                .GetMethods(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Static)
                .Where(m => !m.IsGenericMethod)
                .GroupBy(m => m.Name)
                .ToDictionary(
                    p => p.Key,
                    p => p.GroupBy(r => r.GetParameters().Length).ToDictionary(r => r.Key, r => r.ToList()));
        }

        /// <summary>
        /// Provides the implementation for operations that invoke a member. Classes derived from the <see cref="T:System.Dynamic.DynamicObject"></see> class can override this method to specify dynamic behavior for operations such as calling a method.
        /// </summary>
        /// <param name="binder">Provides information about the dynamic operation. The binder.Name property provides the name of the member on which the dynamic operation is performed. For example, for the statement sampleObject.SampleMethod(100), where sampleObject is an instance of the class derived from the <see cref="T:System.Dynamic.DynamicObject"></see> class, binder.Name returns &amp;quot;SampleMethod&amp;quot;. The binder.IgnoreCase property specifies whether the member name is case-sensitive.</param>
        /// <param name="args">The arguments that are passed to the object member during the invoke operation. For example, for the statement sampleObject.SampleMethod(100), where sampleObject is derived from the <see cref="T:System.Dynamic.DynamicObject"></see> class, args[0] is equal to 100.</param>
        /// <param name="result">The result of the member invocation.</param>
        /// <returns>true if the operation is successful; otherwise, false. If this method returns false, the run-time binder of the language determines the behavior. (In most cases, a language-specific run-time exception is thrown.)</returns>
        /// <autogeneratedoc />
        public override bool TryInvokeMember(InvokeMemberBinder binder, object[] args, out object result)
        {
            // Get type args of the call
            var typeArgs = ExposedObjectHelper.GetTypeArgs(binder);
            if (typeArgs != null && typeArgs.Length == 0) typeArgs = null;

            //
            // Try to call a non-generic instance method
            //
            if (typeArgs == null
                    && _staticMethods.ContainsKey(binder.Name)
                    && _staticMethods[binder.Name].ContainsKey(args.Length)
                    && ExposedObjectHelper.InvokeBestMethod(args, null, _staticMethods[binder.Name][args.Length], out result))
            {
                return true;
            }

            //
            // Try to call a generic instance method
            //
            if (typeArgs != null && _staticMethods.ContainsKey(binder.Name) && _staticMethods[binder.Name].ContainsKey(args.Length))
            {
                var methods = new List<MethodInfo>();

                foreach (var method in _genStaticMethods[binder.Name][args.Length])
                {
                    if (method.GetGenericArguments().Length == typeArgs.Length)
                    {
                        methods.Add(method.MakeGenericMethod(typeArgs));
                    }
                }

                if (ExposedObjectHelper.InvokeBestMethod(args, null, methods, out result))
                {
                    return true;
                }
            }

            result = null;
            return false;
        }
        /// <summary>
        /// Provides the implementation for operations that set member values. Classes derived from the <see cref="T:System.Dynamic.DynamicObject"></see> class can override this method to specify dynamic behavior for operations such as setting a value for a property.
        /// </summary>
        /// <param name="binder">Provides information about the object that called the dynamic operation. The binder.Name property provides the name of the member to which the value is being assigned. For example, for the statement sampleObject.SampleProperty = &amp;quot;Test&amp;quot;, where sampleObject is an instance of the class derived from the <see cref="T:System.Dynamic.DynamicObject"></see> class, binder.Name returns &amp;quot;SampleProperty&amp;quot;. The binder.IgnoreCase property specifies whether the member name is case-sensitive.</param>
        /// <param name="value">The value to set to the member. For example, for sampleObject.SampleProperty = &amp;quot;Test&amp;quot;, where sampleObject is an instance of the class derived from the <see cref="T:System.Dynamic.DynamicObject"></see> class, the value is &amp;quot;Test&amp;quot;.</param>
        /// <returns>true if the operation is successful; otherwise, false. If this method returns false, the run-time binder of the language determines the behavior. (In most cases, a language-specific run-time exception is thrown.)</returns>
        /// <autogeneratedoc />
        public override bool TrySetMember(SetMemberBinder binder, object value)
        {
            var propertyInfo = PropertyInfo(binder.Name, _type);

            if (propertyInfo != null)
            {
                propertyInfo.SetValue(null, value, null);
                return true;
            }

            var fieldInfo = FieldInfo(binder.Name, _type);

            if (fieldInfo != null)
            {
                fieldInfo.SetValue(null, value);
                return true;
            }

            return false;
        }

        /// <summary>
        /// Provides the implementation for operations that get member values. Classes derived from the <see cref="T:System.Dynamic.DynamicObject"></see> class can override this method to specify dynamic behavior for operations such as getting a value for a property.
        /// </summary>
        /// <param name="binder">Provides information about the object that called the dynamic operation. The binder.Name property provides the name of the member on which the dynamic operation is performed. For example, for the Console.WriteLine(sampleObject.SampleProperty) statement, where sampleObject is an instance of the class derived from the <see cref="T:System.Dynamic.DynamicObject"></see> class, binder.Name returns &amp;quot;SampleProperty&amp;quot;. The binder.IgnoreCase property specifies whether the member name is case-sensitive.</param>
        /// <param name="result">The result of the get operation. For example, if the method is called for a property, you can assign the property value to result.</param>
        /// <returns>true if the operation is successful; otherwise, false. If this method returns false, the run-time binder of the language determines the behavior. (In most cases, a run-time exception is thrown.)</returns>
        /// <autogeneratedoc />
        public override bool TryGetMember(GetMemberBinder binder, out object result)
        {
            var propertyInfo = PropertyInfo(binder.Name, _type);

            if (propertyInfo != null)
            {
                result = GetValueOrExposedObject(propertyInfo);
                return true;
            }

            var fieldInfo = FieldInfo(binder.Name, _type);

            if (fieldInfo != null)
            {
                result = GetValueOrExposedObject(fieldInfo);
                return true;
            }

            var nestedType = _type.GetNestedType(binder.Name, BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Static);

            if(nestedType != null)
            {
                result = From(nestedType);
                return true;
            }

            result = null;
            return false;
        }

        private PropertyInfo PropertyInfo(string name, Type type)
        {
            while (true)
            {
                if (type == null) 
                    return null;

                var propertyInfo = type.GetProperty(name, BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance);

                if (propertyInfo != null) 
                    return propertyInfo;

                type = type.BaseType;
            }
        }

        private FieldInfo FieldInfo(string name, Type type)
        {
            while (true)
            {
                if (type == null) 
                    return null;

                var fieldInfo = type.GetField(name, BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance);

                if (fieldInfo != null) 
                    return fieldInfo;

                type = type.BaseType;
            }
        }

        /// <summary>
        /// From the specified type.
        /// </summary>
        /// <param name="type">The type.</param>
        /// <returns>dynamic.</returns>
        /// <autogeneratedoc />
        public static dynamic From(Type type)
        {
            return new ExposedClass(type);
        }

        public static dynamic From(string name, Assembly assembly)
        {
            foreach (var type in assembly.GetTypes())
            {
                if(type.FullName.Equals(name, StringComparison.InvariantCultureIgnoreCase))
                    return From(type); 
            }

            throw new Exception($"Type {name} was not found.");
        }

        private object GetValueOrExposedObject(PropertyInfo info)
        {
            if (info.PropertyType.IsPrimitive)
                return info.GetValue(null, null);
            if(typeof(string) == info.PropertyType)
                return info.GetValue(null, null);
            return From(info.GetValue(null, null).GetType());
        }

        private object GetValueOrExposedObject(FieldInfo info)
        {
            if (info.FieldType.IsPrimitive)
                return info.GetValue(null);
            if(typeof(string) == info.FieldType)
                return info.GetValue(null);
            return From(info.GetValue(null).GetType());
        }
    }
}